export const MenuRootId = {
  MENU_HOME_ID: 'ROOT_MENU_HOME_ID',
  MENU_TEMPLATE_ID: 'ROOT_MENU_TEMPLATE_ID',
  MENU_RULE_ID: 'ROOT_MENU_RULE_ID',
  MENU_PROJECT_ID: 'ROOT_MENU_PROJECT_ID',
  MENU_ASSETS_ID: 'ROOT_MENU_ASSETS_ID',
  MENU_TRASH_ID: 'ROOT_MENU_TRASH_ID',
  MENU_TEAM_ID: 'ROOT_MENU_TEAM_ID',
};
